# Generated by Django 4.2.7 on 2025-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="电影名称")),
                ("release_date", models.DateField(verbose_name="上映日期")),
                ("budget", models.BigIntegerField(verbose_name="预算（美元）")),
                ("revenue", models.BigIntegerField(verbose_name="票房（美元）")),
                ("runtime", models.IntegerField(verbose_name="片长（分钟）")),
                ("vote_average", models.FloatField(verbose_name="平均评分")),
                ("vote_count", models.IntegerField(verbose_name="评分数量")),
                ("overview", models.TextField(verbose_name="剧情简介")),
                (
                    "poster_path",
                    models.CharField(max_length=200, verbose_name="海报路径"),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
            },
        ),
        migrations.CreateModel(
            name="ProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="制作公司")),
                ("country", models.CharField(max_length=100, verbose_name="国家")),
                (
                    "movies",
                    models.ManyToManyField(
                        related_name="production_companies", to="movie_dashboard.movie"
                    ),
                ),
            ],
            options={
                "verbose_name": "制作公司",
                "verbose_name_plural": "制作公司",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="类型名称")),
                (
                    "movies",
                    models.ManyToManyField(
                        related_name="genres", to="movie_dashboard.movie"
                    ),
                ),
            ],
            options={
                "verbose_name": "电影类型",
                "verbose_name_plural": "电影类型",
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="导演姓名")),
                (
                    "movies",
                    models.ManyToManyField(
                        related_name="directors", to="movie_dashboard.movie"
                    ),
                ),
            ],
            options={
                "verbose_name": "导演",
                "verbose_name_plural": "导演",
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="演员姓名")),
                (
                    "movies",
                    models.ManyToManyField(
                        related_name="actors", to="movie_dashboard.movie"
                    ),
                ),
            ],
            options={
                "verbose_name": "演员",
                "verbose_name_plural": "演员",
            },
        ),
    ]
